apiVersion: apps/v1
kind: Deployment
metadata:
  name: thesis-utils-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: thesis-utils
  template:
    metadata:
      labels:
        component: thesis-utils
    spec:
      containers:
        - name: thesis-utils
          image: 'thesis-utils:01262111'
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: thesis-configmap
          env:
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: miniosecret
